name: Deploy Production bot via CDK

on:
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: Production Environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'  # you can specify the version you want

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/test/test-requirements.txt
      
      - name: Run unit tests
        run: |
          cd ./src/
          python -m pytest -v -s 

  deploy:
    runs-on: ubuntu-latest  
    environment: Production Environment
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk
      
      - name: Setup Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'  # you can specify the version you want

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run discord-commands.py
        run: python commands/register_commands.py prod
        env: 
          PROD_DISCORD_TOKEN: ${{ secrets.PROD_DISCORD_TOKEN }}
          PROD_DISCORD_APPLICATION_ID: ${{ secrets.PROD_DISCORD_APPLICATION_ID }}
          PROD_DISCORD_PUBLIC_KEY: ${{ secrets.PROD_DISCORD_PUBLIC_KEY }}
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy CDK stack
        run: cdk deploy ProdBookClubBotStack --require-approval never
        env:
          ENVIRONMENT: prod
          PROD_DISCORD_TOKEN: ${{ secrets.PROD_DISCORD_TOKEN }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}